title: MTG:Toulouse
description: > # this means to ignore newlines until "baseurl:"
  MTG:Toulouse
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mtg-toulouse.org" # the base hostname & protocol for your site

#navigation
navigationLinks:
 - {url: "/", text: "Accueil"}
 #- {url: "/agenda/", text: "Agenda"}
 #- {url: "/speakers/", text: "Speakers"}
 #- {url: "/sponsors", text: "Partenaires"}
 - {url: "/association", text: "L'association"}
 #- {url: "/faq/", text: "FAQ"}
 - {url: "/coc", text: "Code de conduite"}

pageHeaders:
#  agenda: {bg: "#00a1f1", font: "#fff", title: "Agenda"}
#  speakers: {bg: "#f65314", font: "#fff", title: "Speakers"}
  association: {bg: "#7cbb00", font: "#fff", title: "L'Association"}
  faq: {bg: "#ffbb00", font: "#fff", title: "Foire Aux Questions"}
  coc: {bg: "#f65314", font: "#fff", title: "Code de Conduite"}
  sessions: {bg: "#7cbb00", font: "#fff"}
#  sponsors: {bg: "#ffbb00", font: "#fff", title: "Communautés"}
  statistics: {bg: "#7cbb00", font: "#fff"}
  
  
collections:
  sessions:
    output: true
    permalink: /sessions/:title

defaults:
  -
    scope:
      path: ""
      type: "sessions"
    values:
      layout: "session"
      css: agenda

logo: "../css/style/img/icon-large.png"

#google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-datapage-generator

page_gen-dirs: false

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: youtube
#    url: https://www.youtube.com/c/MUGTVFrance
  - title: twitter
    url: https://twitter.com/MTG_Toulouse

share:
  - platform: twitter
    url: "https://twitter.com/share?url=https:%2f%2fwww.mtg-toulouse.org&text="
    text: "Je viens de rejoindre @MTG_Toulouse !"

# Build settings
markdown: kramdown
permalink: pretty
